server:
  port: 9001
  forward-headers-strategy: native

spring:
  kafka:
    bootstrap-servers: kafka:9092
    streams:
      application-id: order-manager
      properties:
        default.deserialization.exception.handler: org.apache.kafka.streams.errors.LogAndContinueExceptionHandler
    producer:
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      schema.registry.url: http://localhost:8085
      value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicRecordNameStrategy
    topics:
      orders: orders
      events: events
